hosts:
  intranet:
    addr: 10.37.0.3
    ports:
      - 80
      - 443
  gateway:
    addr: 192.168.1.1
    ports:
      - 22
      - 80
  google:
    addr: google.com
    ports:
      - 443
      - 80
#common_port: 9999