#!/usr/bin/python

import sys

from core.cli import Cli
from services.monitor_services import Monitor_Service
from services.spider_service import Spider_service
from utils.file_utils import FileOutPut


def main():
	

	args = Cli.parse_args()


	

	if (args.active or args.inactive) and not args.monitor:
		print("'--monitor or -m' it's necessary")
		sys.exit(1)

	if (args.active or args.inactive) and not args.inventory:
		print("Erro: It's necessary supply to inventory file with '--inventory' or '-f'")
		sys.exit(1)

	if args.spider and not (args.domain and args.url):
		print("Erro: To use --htmlparser, supply --url (or -u) and --domain (or -d)")
		sys.exit(1)

	if args.active and args.inactive:
		print('não usar os dois juntos')
		sys.exit(1)

	function_map = {

		'active': lambda: Monitor_Service(args.inventory).get_active(),
		'inactive': lambda: Monitor_Service(args.inventory).get_inactive(),
		'spider': lambda: Spider_service(args.url,args.domain).get_parser()
	}

	if args.active:

		function_map['active']()

	elif args.inactive:
    
		function_map['inactive']()
		

	elif args.spider:
		
		parser_instance  = Spider_service(args.url,args.domain)
		parser_instance.get_parser()
		
		if args.output:
			FileOutPut.output_file(args.output,parser_instance.emails_found, parser_instance.visited_links)
		
        
	else:
		#args.print_help()
		pass
if __name__ == '__main__':
    main()



